# Generated by Django 5.1.15 on 2026-09-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('photo', models.FileField(upload_to='founder/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('period', models.CharField(blank=True, max_length=50)),
                ('features', models.JSONField(default=list)),
                ('highlighted', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('value', models.IntegerField()),
                ('suffix', models.CharField(blank=True, max_length=16)),
                ('label', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('photo', models.FileField(upload_to='team/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('whatsapp', models.CharField(blank=True, max_length=32)),
                ('linkedin', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=200)),
                ('avatar', models.FileField(upload_to='testimonials/')),
            ],
        ),
        migrations.CreateModel(
            name='InsightArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=300)),
                ('body', models.JSONField(default=list)),
                ('cover_image', models.FileField(upload_to='insights/')),
                ('publish_date', models.DateField()),
                ('touches_compliance', models.BooleanField(default=False)),
                ('related_insights', models.ManyToManyField(blank=True, to='content.insightarticle')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('obligations', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('source_name', models.CharField(blank=True, max_length=200)),
                ('hero_image', models.FileField(upload_to='compliance/')),
                ('related_insights', models.ManyToManyField(blank=True, related_name='related_compliance_areas', to='content.insightarticle')),
            ],
            options={
                'verbose_name_plural': 'compliance areas',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('pillar', models.CharField(choices=[('residency-solutions', 'Residency Solutions'), ('business-incorporation', 'Business Incorporation'), ('compliance-governance', 'Compliance & Governance')], max_length=32)),
                ('icon', models.CharField(max_length=32)),
                ('summary', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('included', models.JSONField(default=list)),
                ('hero_image', models.FileField(upload_to='services/')),
                ('stats', models.JSONField(default=list)),
                ('related_insights', models.ManyToManyField(blank=True, related_name='related_services', to='content.insightarticle')),
                ('team_members', models.ManyToManyField(blank=True, related_name='services', to='content.teammember')),
            ],
            options={
                'ordering': ['pillar', 'title'],
            },
        ),
    ]
