# Generated by Django 5.1.15 on 2026-09-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='faqs',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='service',
            name='process',
            field=models.JSONField(default=list),
        ),
    ]
