# Generated by Django 5.1.15 on 2026-09-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_service_faqs_service_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='philosophy_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
