# Generated by Django 5.1.15 on 2026-09-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_service_philosophy_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancearea',
            name='included',
            field=models.JSONField(default=list),
        ),
    ]
