# Generated by Django 5.1.15 on 2026-09-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_compliancearea_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cta_label',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
