# Generated by Django 5.1.15 on 2026-09-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_service_cta_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='faqs',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='process',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
