# Generated by Django 5.1.15 on 2026-09-21 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_service_faqs_alter_service_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingtier',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='pricing_tiers', to='content.service'),
        ),
        migrations.CreateModel(
            name='ServiceFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('file', 'File'), ('checkbox', 'Checkbox')], default='text', max_length=16)),
                ('required', models.BooleanField(default=True)),
                ('options', models.JSONField(blank=True, default=list)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='content.service')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('service', 'key')},
            },
        ),
    ]
