# Generated by Django 5.1.15 on 2026-09-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('main_service', models.CharField(choices=[('incorporation', 'Incorporation'), ('residency', 'Residency'), ('compliance', 'Compliance'), ('partner', 'Partner with Us'), ('general', 'General Enquiry')], max_length=20)),
                ('sub_service', models.CharField(blank=True, max_length=100)),
                ('requirement', models.TextField()),
                ('preferred_contact_method', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('phone', 'Phone'), ('email', 'Email')], default='whatsapp', max_length=10)),
                ('preferred_contact_time', models.CharField(blank=True, max_length=100)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leads/%Y/%m/')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal', 'Proposal / Quotation'), ('documentation', 'Documentation'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('lost', 'Lost / Not Qualified')], default='new', max_length=20)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('device_type', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
